exports.port = 8888;
exports.token = 'super_sicret_parol';
exports.dbName = 'sessions';
exports.adminLogins = ['Bank'];
exports.userDB = 'game_users';
exports.opsDB = 'game_ops';
exports.projectGoups = ['01','02','03','04','05','06'];
exports.tables = ['X', 'Y', 'Z', 'A', 'B', 'C','D'];
exports.newProjects = ['Project_1', 'Project_2', 'Project_3', 'Project_4', 'Project_5', 'Project_6', 'Project_7', 'Project_8', 'Project_9', 'Project_10']
exports.licExp = ['Оплата труда', 'Оплата проектных услуг', 'Возврат инвестиции'];
exports.lic = [];
exports.creditLimit = 300;
exports.subsidyLimit = 3000;
exports.priceOfExtension = 10;
exports.bankProcent = 5;
exports.subsidyProcent = 2;
exports.objects = [{value:'Продукт', status: 0}, {value:'Вторсырье', status: 0}, {value:'Буква', status: 0}, {value:'Слово', status: 0}, {value:'Инвестиции', status: 1}];